Fetch ruby gems as part of setup
* Also exit from the script (return) in the event of errors.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -27,10 +27,22 @@ if [[ -z ${result} ]]; then
     export PATH=${CURRENT_PATH}:$PATH
     say "$(ok "Setup path: ${CURRENT_PATH}")"
 
+    say "Fetching Ruby gems"
+    pushd "${CURRENT_PATH}/.."
+    bundle
+    if [ $? -ne 0 ]; then
+        say "$(error "Failed to download Ruby gems")"
+        return
+    else
+        say "$(ok "Ruby gems installed")"
+    fi
+    popd
+
     say "Fetching course container from dockerhub"
     docker pull ${COURSE_IMAGE}
     if [ $? -ne 0 ]; then
         say "$(error "Failed to download course image")"
+        return
     else
         say "$(ok "Downloaded course image")"
     fi
